name: Deployment

on:
    push:
        branches: [ main ]

permissions:
      id-token: write
      contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Embed JSON into HTML
      run: |
            sed -i '85r search.json' results.html

    - name: Minify HTML files
      run: |
          npm install --quiet
          node scripts/minify-html.js .

    - name: Cleanup extra files/folders
      run: |
          rm -rf node_modules
          rm -rf docs
          rm -rf .git
          rm -rf .github
          rm -f .gitignore
          rm -f package.json
          rm -f package-lock.json
          rm -f search.json

    - name: Upload to Cloudflare pages
      uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        command: pages deploy --project-name --branch=main goobill .

    - name: Logout
      run: |
          npx wrangler logout
      if: always()
