name: Deployment

on:
    push:
        branches: [ main ]

permissions:
      id-token: write
      contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: azure/login@v2
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Embed JSON into HTML
      run: |
            sed -i '85r search.json' results.html

    - name: Minify HTML files
      run: |
          npm install --quiet
          node scripts/minify-html.js .
          node scripts/docs-to-html.js ./docs

    - name: Cleanup extra files/folders
      run: |
          rm -rf node_modules
          rm -rf .git
          rm -rf .github
          rm -f package.json
          rm -f package-lock.json
          rm -f search.json

    - name: Drop and Upload to blob storage $web
      uses: azure/cli@v2
      with:
        inlineScript: |
            az storage blob delete-batch --account-name goobill --auth-mode login -s '$web'
            az storage blob upload-batch --account-name goobill --auth-mode login -d '$web' -s .

    - name: logout
      run: |
            az logout
      if: always()
