name: Deployment

on:
    push:
        branches: [ main ]

permissions:
      id-token: write
      contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Move HTML pages
      run: |
        cp -p pages/*.html .

    - name: Embed JSON into results HTML
      run: |
        results_line_number=$(grep -n -m 1 "<script id=\"data-results\" type=\"application/json\">" results.html | sed -n "s/[^0-9]//gp")
        sed -i "${results_line_number}r search.json" results.html

    - name: Node setup
      run: |
        npm install --quiet

    - name: Docs to HTML
      run: |
        find docs -mindepth 2 -type f ! -path "docs/assets/*" -exec mv -t docs {} +
        npm run resize
        npm run convert
        cp -pr docs/*.html .
        cp -pr docs/assets/* ./assets

    - name: Create site map HTML and TXT
      run: |
        for file in ./*.html; do echo "https://goobill.com/$(basename "$file")"; done > sitemap.txt
        results_line_number=$(grep -n -m 1 "<div id=\"results\"" site-map.html | sed -n "s/[^0-9]//gp")
        for file in ./*.html; do echo "<a href=\"$(basename "$file")\">$(basename "$file")</a>"; done | sed -i "${results_line_number}r /dev/stdin" site-map.html

    - name: Minify HTML/JS/CSS files
      run: |
        npm run minify

    - name: Cleanup extra files/folders
      run: |
        rm -rf node_modules
        rm -rf pages
        rm -rf docs
        rm -rf .git
        rm -rf .github
        rm -f README.md
        rm -f .gitignore
        rm -f package.json
        rm -f package-lock.json
        rm -f search.json

    - name: Upload to Cloudflare pages
      uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        command: pages deploy . --project-name=goobill --branch=main
