name: Deployment

on:
    push:
        branches: [ main ]

permissions:
      id-token: write
      contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: azure/login@v2
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Embed JSON into HTML
      run: |
            sed -i '85r search.json' results.html

    - name: Minify HTML files
      run: |
          npm install --quiet
          node scripts/minify-html.js .

    - name: Upload to blob storage $web
      uses: azure/cli@v2
      with:
        inlineScript: |
            az storage blob upload-batch --overwrite true --account-name goobill --auth-mode login -d '$web' -s .

    - name: logout
      run: |
            az logout
      if: always()
