name: Deployment

on:
    push:
        branches: [ main ]

permissions:
      id-token: write
      contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Embed JSON into HTML
      run: |
            sed -i '85r search.json' results.html

    - name: Node setup
      run: |
          npm install --quiet

    - name: Docs to HTML
      run: |
          npm run convert
          cp -p docs/*.html .

    - name: Minify HTML/JS/CSS files
      run: |
          npm run minify

    - name: Cleanup extra files/folders
      run: |
          rm -rf node_modules
          rm -rf docs
          rm -rf .git
          rm -rf .github
          rm -f .gitignore
          rm -f package.json
          rm -f package-lock.json
          rm -f search.json

    - name: Create site map
      run: |
          for file in ./*.html; do echo "https://goobill.com/$(basename "$file")"; done > sitemap.txt

    - name: Upload to Cloudflare pages
      uses: cloudflare/wrangler-action@v3
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        command: pages deploy . --project-name=goobill --branch=main
